### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by steveri**
I think it's time to merge dev into master.  

Edit (below): Never mind, looks like it's okay now.

<s>
But it says "can't automatically merge" which seems bad.  Does anyone know how to fix this?  I'm thinking I/we have to manually do something like this, locally:

% git checkout master
% git merge dev
</s>

### CODE REVIEW

**Comment by steveri** [comment]
Never mind about the merge conflict, looks like it got resolved.

**Comment by alexcarsello** [comment]
It looks like you merged master into dev, rather than merging dev into
master, like you initially said...

Alex

**Comment by alexcarsello** [comment]
Never mind, I see you must've done that to fix the conflict...

Alex

**Comment by steveri** [comment]
correct-o.actually, github did the merge for me, all i did was follow directions included after doing the pull request

**Pull request merged**
