### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by alexcarsello**
Probably a good time to pull dev into master again @steveri

### CODE REVIEW

**Comment by steveri** [comment]
Actually, why don't we just skip this pull and go straight to separate_pad_ring, which should be ready Very Soon...that pull will probably have at least as many diffs and changes, and this extra pull will probably only exacerbate the problem, since it's kind of from a different track...

**Comment by alexcarsello** [comment]
I’m not sure what you mean by this. We have to pull dev into master at some
point. The current plan is to pull separate_pad_ring into dev first, and
then bring dev into master.

**Comment by steveri** [comment]
> We have to pull dev into master at some point. The current plan is to pull separate_pad_ring into dev first, and then bring dev into master.

Yes that is correct.  Sorry if I was unclear! i think we are both on the same page now.

**Comment by steveri** [comment]
Okay I think I managed to replace master with dev entirely, using instructions from stackoverflow https://stackoverflow.com/questions/2862590/how-to-replace-master-branch-in-git-entirely-from-another-branch
```
git checkout dev
git merge -s ours master
git checkout master
git merge dev
```
Now waiting for tests to complete...cross your fingers...

**Pull request merged**
