### PR TITLE
Python based abs unit test and bugfix in test_pe_comp

### PR DESCRIPTION
**Pull request by leonardt**
This pull request includes additions that add a pytest based unit test for the pe, particularly the abs op.

It also includes a bugfix for abs where the `b` input to the adder was wired to `op_b` instead of `0`. See https://github.com/StanfordAHA/CGRAGenerator/pull/40 for more discussion (original PR, this new PR was opened after the base branch was changed).

### CODE REVIEW

**Comment by leonardt** [comment]
Since @steveri has already looked over the PR, I will wait for @kong0329 to approve it before merging. I think you'll mainly want to review the change in https://github.com/StanfordAHA/CGRAGenerator/pull/41/commits/0175dd6d0dc97242e626b3ef3d71540ea79e6021 to see that it looks correct and that it doesn't conflict with anything you're working on.

**Comment by steveri** [comment]
If you don't mind, I'm going to reinstate my system-level/ABS test in your branch as a backup check...if all goes well I will be checking it in and there should be a travis run starting for this in the next half hour or so...

**Comment by leonardt** [comment]
@steveri sounds good to me, more tests the better!

**Comment by steveri** [comment]
@kong0329 @leonardt 
Okay my system-level tests passed locally and in travis, so I'm good
to go.  Full speed ahead! :)
https://travis-ci.org/StanfordAHA/CGRAGenerator/builds/350457679
```
Testing 'abs' (trace is OFF)
  INPUT   0   1   2   3   4   5   6   7   8   9 
  GOLD ---->  1   2   3   4   5   6   7   8   9
  CGRA ---->  1   2   3   4   5   6   7   8   9

Testing 'abs' (trace is OFF)
  INPUT 140 136 107 203 109 246 134  39 204 180 
  GOLD ---->136 107 203 109 246 134  39 204 180
  CGRA ---->136 107 203 109 246 134  39 204 180
```

**Pull request merged**
