### PR TITLE
LT/GE support

### PR DESCRIPTION
**Pull request by steveri**
bsbuilder support for GT/GE/LT/LE operations and variants

### CODE REVIEW

**Comment by steveri** [comment]
> I tested the new bsbuilder.py on
>  Tx0109_gt(const61_61,wire)
> And I got this error...

Well that should have worked...I clearly need to do more testing....should be easy to fix...SR

**Comment by steveri** [comment]
> I tested the new bsbuilder.py on
> Tx0109_gt(const61_61,wire)
> And I got this error...

@Kuree Okay I think it's fixed, try it now

**Comment by steveri** [comment]
Okay, sorry for the false start(s).  Travis is passing again, try it now.

**Comment by Kuree** [comment]
Got this new error:
```
Traceback (most recent call last):
  File "../../bsbuilder.py", line 1693, in <module>
    main()
  File "../../bsbuilder.py", line 409, in main
    if bs_mux(tileno,line, max(0,DBG-1)):
  File "../../bsbuilder.py", line 1030, in bs_mux
    | op_data[op1] | op_data[op2] | op_data[bit0]
KeyError: 'mux'
```

**Pull request merged**
