### PR TITLE
Finish removing analog regs

### PR DESCRIPTION
**Pull request by alexcarsello**
A few things I forgot to do when I removed the analog_regs in my previous PR.

1. Actually delete analog_regfile.vp.
2. Before, I added a parameter to the top level so that we could choose whether or not to include the analog block. I forgot to surround the ports of the analog block in this if statement. That's been fixed now.

### CODE REVIEW

**Comment by steveri** [comment]
?? What's the status of this request?  Looks like all the checks are failing?

**Comment by steveri** [comment]
nvm i know what the problem is i will attempt a fix, hope you don't mind me mucking in your branch...should just be one line in utest.py

**Comment by alexcarsello** [comment]
Don’t worry about it. I just need to rebase off of dev. I brought those
changes into dev yesterday.

**Comment by steveri** [comment]
travis test ran out of time when it was *almost* finished...all tests to that point had passed...ima go ahead and merge...

**Pull request merged**
