### PR TITLE
Refix abs

### PR DESCRIPTION
**Pull request by leonardt**
After chatting with artem today, this is in fact expected behavior for the PE, because it expects the `b` input to be a register with a constant value of 0.

I've reverted the change and updated the test vector generation to take into account a constant register input for `b`, as well as the functional model.

@steveri is there a way to update `utest.py` to take into account the fact the `abs` will have a register with the constant value 0?

### CODE REVIEW

**Comment by leonardt** [comment]
@steveri, scratch that, I think that because utest.py uses the `pe` functional model, it should also be fixed, will merge once travis passes.

**Comment by leonardt** [comment]
@steveri double scratch that, looks like it's failing. I will investigate

**Comment by steveri** [comment]
@leonardt @tema8 @kong0329  !!? Lenny I think your fix is better because it works regardless of what's going on with input b.  Why would this not be the best/correct/expected behavior for abs(a)!!?

**Comment by leonardt** [comment]
@steveri Artem said that there will be an area cost introducing a `mux` for the constant value

**Comment by steveri** [comment]
@tema8 @kong0329  It's muxing in a zero...that's sixteen two-input NAND gates, plus worst-case five inverters to decode the EQ operand...seems like it couldn't be much smaller than that..?  ALSO if we make abs(a) a function of (a,b), how terrible is that going to look in the architecture spec...something like 

`ABS(a,b) == |a| iff b==0 else ABS(a,b) = ???`

..if you like, we can bring in mark and/or pat for an executive decision on this...

**Comment by steveri** [comment]
@tema8 @kong0329 @leonardt ...FYI that last comment was in response to this info from lenny...:

> @steveri Artem said that there will be an area cost introducing a mux for the constant value

**Comment by kong0329** [comment]
@steveri It makes sense. If we are allowed to use abs(a) only when b is 0, it may not be the best.
We can talk with Mark.

**Comment by tema8** [comment]
Steve,

Abs will always be a function of a: Abs(a). 
Since Abs() doesn't use b, it doesn't matter that b is doing. So we can put b into "CONSTANT" mode that drive 0. 
This will be a rule for tile configuration - with ABS, b has to be configured as constant with 0.

Explicitly assigning "b" to 0 adds an extra input to a MUX in front of an added which will make it bigger. this increase will be small, but keep in mind that it'll be for every tile, and thus will get multiplied by 1000's. Also this mux input is redundant given that b can already provide 0.

Finally, my main concern was that the original change by @leonardt could have broken the generator for a case of SAD instruction instead of ABS. I have reviewed the change and it's safe, the generator will work in both case. So it's fine to keep that assignment if you find it convenient and don't mind the redundant code.

**Comment by steveri** [comment]
Artem: Given that there is a multiplier in the tile, among other things, how much percent-area would this add to the overall chip?   Is it closer to 10%, 1%, 0.1% or much-less-than-0.1%?

**Comment by tema8** [comment]
Steve, I haven't done this experiment, but it certainly will be small

**Comment by steveri** [comment]
1. Given that the area impact is small, and it doesn't break SAD, I vote that we go with the original fix from @leonardt 

2. Why are the checks failing now?

**Comment by kong0329** [comment]
@steveri Does generated bitstream file for op_eq assert op_b to be zero? Otherwise, it won't work correctly

**Comment by leonardt** [comment]
@steveri the checks fail because I removed the change, so utest.py with the enabled `abs` test no longer passes (the state before the change I made). 

If we're going with the original fix, I am going to close this pull request, since we don't need any changes.

**Comment by steveri** [comment]
@kongty we're getting rid of op_eq, it doesn't exist anymore...for op_abs, we're going with lenny's original fix of asserting op_b to be zero.

**Pull request closed without merging**
